baseURL = "http://www.example.com"
title = "LTMSHA"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

disqusShortname = ""
googleAnalytics = ""

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "fr"

[params.info]
description = "ligue de tennis métropolitaine de saint-hyacinthe amateur"
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon.ico"
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "MunifTanjim"
startYear = "2017"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "02 Jan 2006"
listDateFormat = "02 Jan 2006"
archiveDateFormat = "02 Jan"
hideEntryNavigation = ["page"] # boolean / array of sections
showReadingTime = true
taxonomyCloudShuffle = true
accentColor = "#d35f5f"
hideMainMenu = false

[params.sidebar]
enable = true

[params.widgets]
homepage = ["recent_posts"]
sidebar = ["logo","sidebar_menu","derniere_partie","taxonomy_cloud"]
footer = ["social_menu"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
codepen = "MunifTanjim"
email = "contact@example.com"
facebook = "MunifTanjim"
github = "MunifTanjim"
gitlab = "MunifTanjim"
instagram = "MunifTanjim"
linkedin = "muniftanjim"
twitter = "MunifTanjim"
telegram = "MunifTanjim"
google_scholar = "qc6CJjYAAAAJ"

[params.comments]
enable = false

[params.comments.staticman]
enable = false
apiEndpoint = "https://api.staticman.net/v2/entry"
maxDepth = 2

[params.comments.staticman.github]
username = "MunifTanjim"
repository = "minimo"
branch = "master"

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"

[[menu.main]]
name = "Repo"
weight = -10
identifier = "repository"
url = "https://github.com/MunifTanjim/minimo"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.fr]
lang = "fr"
languageName = "Francais"
weight = 1
